require "open-uri"
require "nokogiri"
require "pry"
require "rb-readline"
require "colorize"

require_relative "box_office2/version"
require_relative "box_office2/cli"
require_relative "box_office2/movie_list"
require_relative "box_office2/movie"
require_relative "box_office2/scrapper"
